CREATE TABLE public.token_usage_logs (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    user_id uuid NULL,
    prompt_tokens integer NULL,
    candidates_tokens integer NULL,
    total_tokens integer NULL,
    analysis_id uuid NULL,
    CONSTRAINT token_usage_logs_pkey PRIMARY KEY (id),
    CONSTRAINT token_usage_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL
);

ALTER TABLE public.token_usage_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow authenticated users to insert their own usage"
ON public.token_usage_logs
FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Enable read access for service_role"
ON public.token_usage_logs
FOR SELECT
TO service_role
USING (true);
