-- 1. Création de la table pour stocker les feedbacks
CREATE TABLE public.feedbacks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz DEFAULT timezone('utc'::TEXT, now()) NOT NULL,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  rating SMALLINT CHECK (rating >= 1 AND rating <= 5),
  comment TEXT,
  -- Métadonnées optionnelles
  user_email TEXT,
  user_name TEXT
);

-- 2. Activation de la Row Level Security (RLS) pour la sécurité
ALTER TABLE public.feedbacks ENABLE ROW LEVEL SECURITY;

-- 3. Création des politiques d'accès
-- Les utilisateurs peuvent insérer leur propre feedback
CREATE POLICY "Users can insert their own feedback"
ON public.feedbacks FOR INSERT
TO authenticated
WITH CHECK (
  (auth.uid() = user_id) AND
  (NOT EXISTS (SELECT 1 FROM public.deleted_users WHERE user_id = auth.uid()))
);

-- Les utilisateurs peuvent voir leurs propres feedbacks (si vous voulez leur montrer un jour)
CREATE POLICY "Users can view their own feedback"
ON public.feedbacks FOR SELECT
TO authenticated
USING (
  (auth.uid() = user_id) AND
  (NOT EXISTS (SELECT 1 FROM public.deleted_users WHERE user_id = auth.uid()))
);

-- Le service_role (utilisé par les fonctions server-side) et les admins peuvent tout voir
CREATE POLICY "Admins can view all feedback"
ON public.feedbacks FOR SELECT
TO service_role
USING (true);

-- 4. Ajout de commentaires pour la clarté
COMMENT ON TABLE public.feedbacks IS 'Table pour collecter les feedbacks des utilisateurs (notes et commentaires).';
COMMENT ON COLUMN public.feedbacks.rating IS 'Note de 1 à 5 étoiles.';